### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by jnizet** [loicfrering/ruban#14]
Hi Loïc.

That's more a question than an issue, but I thought the best place to ask it was here.

I plan to submit a PR to https://github.com/melix/deck2pdf, which allows exporting various kinds of HTML slideshows to PDF, in order for the project to support ruban (which we use and love, BTW. Thanks!). Here's [the result of the export](https://www.dropbox.com/s/nwjnj3i7wiy5jo1/test-ruban.pdf) on the index.html file of ruban.

You can see the commit I'd like to submit [here](https://github.com/jnizet/deck2pdf/commit/b32634bf72cedf3b9bb0580832ad646d53bf5410). 

First, as I'm far from knowing ruban as much as you do, feel free to comment.

Second, I have some concerns about the implementation, because 
- it relies on internals of the implementation (access to `ruban.$ruban`, `ruban.$current`, `ruban.$sections`, `ruban.index`) rather than "public" methods (that don't exist) like `isLastSlide()`, `isLastStep()` or `disableTransitions()`
- it relies on the existence of a global variable `ruban`, which exists in the sample index.html page, but my not exist in all slideshows. That's less of a problem though, as I have documented it in the README.

Do you care enough , and think it might be a good idea to add these missing functions? I can submit a PR if you want.

**Comment by loicfrering** [comment]
Hi @jnizet, `deck2pdf` looks great, the resulting PDF is really nice! It sure is a good idea to add these public functions rather than rely on internal details: I'm going to push some commits to implement the 3 functions you mentioned.

Thanks for reaching out and for using Ruban!

**Comment by loicfrering** [comment]
Here are the commits with the new functions: e2cbfc8...0f3398f. I'll release a new version soon! In the meantime, let me know if it suits your needs and if you need any additional help or information.

Thanks again @jnizet!

**Comment by jnizet** [comment]
Great. Works fine. I updated the commit and added a new one allowing to generate one slide per section instead of one slide per step.

See the two commits in https://github.com/jnizet/deck2pdf/commits/feat/ruban

If that suits you, I'll wait for the new release of ruban, and then submit my PR to deck2pdf.

**Comment by jnizet** [comment]
Hey Loïc. Do you plan to make a release? I'm still waiting for it to submit my PR to deck2pdf.

**Comment by loicfrering** [comment]
Hi @jnizet, I just released v0.3.2 with the additional functions. I'm very sorry for the delay, feel free to submit the PR to deck2pdf: everything should be okay on Ruban's side.

Thanks a lot!

**Comment by jnizet** [comment]
Great. Thank you. PR submitted and merged: https://github.com/melix/deck2pdf/pull/30.
New version not release yet, though.
